apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-alps-test
  namespace: alps-test
spec:
  storageClassName: database
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
