apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pages
  name: pages
spec:
  volumes:
    - name: secret-vol
      secret:
        secretName: pages-secret
  containers:
  - image: dellcloud/pages:1.0
    name: pages
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - name: secret-vol
        mountPath: /etc/config