apiVersion: v1
kind: Pod
metadata:
  labels:
    run: busybox
  name: busybox
spec:
  containers:
    - image: busybox
      name: busybox
      imagePullPolicy: IfNotPresent
      command: ["/bin/sh"]
      args: ["-c","echo Hello from pages Yellow Pages"]